DjangoFrame/DjangoFrame/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),  # 富文本编辑器
    url(r'^search/', include('haystack.urls')),  # 全文检索
    # url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
    url(r'^user/', include('user.urls', namespace='user')),  # 用户模块
    url(r'^order/', include('order.urls', namespace='order'))  # 订单模块
]

DjangoFrame/apps/user/urls.py
from django.conf.urls import url
from user.views import RegisterView, ActiveView, LoginView, LogoutView, UserInfoView, UserOrderView, AddressView

urlpatterns = [

    url(r'^register$', RegisterView.as_view(), name='register'),  # 注册

    url(r'^active/(?P<token>.*)$', ActiveView.as_view(), name='active'),  # 激活

    url(r'^login$', LoginView.as_view(), name='login'),  # 登录

    url(r'^logout$', LogoutView.as_view(), name='logout'),  # 退出登录

    url(r'^$', UserInfoView.as_view(), name='user'),  # 用户中心-信息页

    url(r'^order/(?P<page>\d+)$', UserOrderView.as_view(), name='order'),  # 用户中心-订单页

    url(r'^address$', AddressView.as_view(), name='address'),  # 用户中心-地址页

]

DjangoFrame/templates/base.html
{# 注册 登录 首页 #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {% load staticfiles %}
    <link rel="shortcut icon" href="{% static "favicon.ico" %}">
    {# 网页标题块 #}
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {# 网页顶部引入文件块 #}
	{% block topfiles %}{% endblock topfiles %}
</head>
<body>
{# 网页顶部欢迎信息块 #}
{% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                {% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{ user.username }}</em>
                    <span>|</span>
					<a href="{% url 'user:logout' %}">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:show' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' 1 %}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
{% endblock header_con %}

{# 网页搜索框块 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
            <form method="get" action="/search">
			<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			<input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:show' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
{% endblock search_bar %}

{# 网页主体内容块 #}
{% block body %}{% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    {# 网页底部html元素块 #}
    {% block bottom %}{% endblock bottom %}
    {# 网页底部引入文件块 #}
	{% block bottomfiles %}{% endblock bottomfiles %}
</body>
</html>

DjangoFrame/templates/base_detail_list.html
{# 详情页 列表页 #}
{% extends 'base.html' %}
{% block body %}
    <div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
                    {% for type in types %}
					<li><a href="{% url 'goods:list' type.id 1 %}" class="{{ type.logo }}">{{ type.name }}</a></li>
					{% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
    {# 详情页 列表页 主体内容块 #}
    {% block main_content %}{% endblock main_content %}
{% endblock body %}

DjangoFrame/templates/base_no_cart.html
{# 购物车 提交订单 #}
{% extends 'base.html' %}
{% load staticfiles %}
{# 网页搜索框块 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{% block page_title %}{% endblock page_title %}</div>
		<div class="search_con fr">
			<form method="get" action="/search">
			<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			<input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
	</div>
{% endblock search_bar %}

DjangoFrame/templates/detail.html
{% extends 'base_detail_list.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-商品详情{% endblock title %}
{% block main_content %}
	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{ sku.type.name }}</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{{ sku.image.url }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ sku.name }}</h3>
			<p>{{ sku.desc }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ sku.price }}</em></span>
				<span class="show_unit">单  位：{{ sku.unite }}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>	
				</div> 
			</div>
            <div>
                <div>其他规格:</div>
                <div>
                    {% for sku in same_spu_skus %}
                        <a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a>
                    {% endfor %}
                </div>
            </div>
			<div class="total">总价：<em>{{ sku.price }}元</em></div>
			<div class="operate_btn">
                {% csrf_token %}
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" sku_id="{{ sku.id }}" class="add_cart" id="add_cart">加入购物车</a>
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for sku in new_skus %}
					<li>
						<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
						<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
						<div class="prize">￥{{ sku.price }}</div>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active" id="tag_detail">商品介绍</li>
				<li id="tag_comment">评论</li>
			</ul>

			<div class="tab_content" id="tab_detail">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ sku.goods.detail|safe }}</dd>
                </dl>
			</div>

            <div class="tab_content" id="tab_comment" style="display: none;">
				<dl>
                    {% for order_sku in order_skus %}
					<dt>评论时间：{{ order_sku.update_time }}&nbsp;&nbsp;用户名：{{ order_sku.order.user.username }}</dt>
					<dd>评论内容：{{ order_sku.comment }}</dd>
                    {% empty %}
                        暂无评论信息
                    {% endfor %}
                </dl>
			</div>
		</div>
	</div>
{% endblock main_content %}
{% block bottom %}
	<div class="add_jump"></div>
{% endblock bottom %}
{% block bottomfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js'  %}"></script>
	<script type="text/javascript">
        $('#tag_detail').click(function () {
            $(this).addClass('active')
            $('#tag_comment').removeClass('active')
            $('#tab_detail').show()
            $('#tab_comment').hide()
        })
        $('#tag_comment').click(function () {
            $(this).addClass('active')
            $('#tag_detail').removeClass('active')
            $('#tab_detail').hide()
            $('#tab_comment').show()
        })
        // 计算商品的总价
        function update_sku_amount() {
            // 获取商品的价格和数量
            count = $('.num_show').val()
            price = $('.show_pirze').children('em').text()
            // 计算商品的小计
            count = parseInt(count)
            price = parseFloat(price)
            amount = price*count
            // 设置商品的小计
            $('.total').children('em').text(amount.toFixed(2)+'元')
        }

        // 商品数目增加
        $('.add').click(function () {
            // 获取商品的数量
            count = $('.num_show').val()
            // 加1
            count = parseInt(count)+1
            // 设置商品的数量
            $('.num_show').val(count)
            // 更新总价
            update_sku_amount()
        })

        // 商品数目减少
        $('.minus').click(function () {
            // 获取商品的数量
            count = $('.num_show').val()
            // 减1
            count = parseInt(count)-1
            if (count <= 0){
                count = 1
            }
            // 设置商品的数量
            $('.num_show').val(count)
            // 更新总价
            update_sku_amount()
        })

        // 手动输入商品数目
        $('.num_show').blur(function () {
            // 获取用户输入商品的数量
            count = $(this).val()
            // 校验
            if (isNaN(count) || count.trim().length == 0 || parseInt(count) <= 0){
                count = 1
            }
            // 设置商品的数量
            $(this).val(parseInt(count))
            // 更新总价
            update_sku_amount()
        })

        // 获取 add_cart a元素左上角的坐标
		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

        // 获取show_count div元素左上角的坐标
		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;


		$('#add_cart').click(function(){
            // 获取商品的id和商品的数量
            count = $('.num_show').val()
            sku_id = $(this).attr('sku_id') // prop attr
            csrf = $('input[name="csrfmiddlewaretoken"]').val()
            // 组织参数
            params = {'sku_id':sku_id, 'count':count, 'csrfmiddlewaretoken':csrf}
            // 发起ajax post请求，访问/cart/add, 传递参数: sku_id count
            $.post('/cart/add', params, function (data) {
                if (data.res == 5){
                    // 添加成功
                    $(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
                    $(".add_jump").stop().animate({
                        'left': $to_y+7,
                        'top': $to_x+7},
                        "fast", function() {
                            $(".add_jump").fadeOut('fast',function(){
                                // 重新设置用户购物车中商品的条目数
                                $('#show_count').html(data.cart_count);
                            });
                    });
                }
                else{
                    // 添加失败
                    alert(data.errmsg)
                }
            })
		})
	</script>
{% endblock bottomfiles %}

DjangoFrame/templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-登录{% endblock title %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
	<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>
	</div>
	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="#">立即注册</a>
				</div>
				<div class="form_input">
                    {# 页面的form不设置action, 提交表单时是访问浏览器地址栏中的地址 #}
					<form method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" value="{{ username }}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="remember" {{ checked }}>
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
    {{ errmsg }}
{% endblock body %}

DjangoFrame/templates/place_order.html
{% extends 'base_no_cart.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-提交订单{% endblock title %}
{% block page_title %}提交订单{% endblock page_title %}
{% block body %}
	<h3 class="common_title">确认收货地址</h3>

	<div class="common_list_con clearfix">
		<dl>
			<dt>寄送到：</dt>
            {% for addr in addrs %}
			<dd><input type="radio" name="addr_id" value="{{ addr.id }}" {% if addr.is_default %}checked{% endif %}>{{ addr.addr }}（{{ addr.receiver }} 收） {{ addr.phone }}</dd>
		    {% empty %}
                <dd>没有收货地址信息</dd>
            {% endfor %}
        </dl>
		<a href="{% url 'user:address' %}" class="edit_site">编辑收货地址</a>

	</div>
	
	<h3 class="common_title">支付方式</h3>	
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" name="pay_style" value="1" checked>
			<label class="cash">货到付款</label>
			<input type="radio" name="pay_style" value="2">
			<label class="weixin">微信支付</label>
			<input type="radio" name="pay_style" value="3">
			<label class="zhifubao"></label>
			<input type="radio" name="pay_style" value="4">
			<label class="bank">银行卡支付</label>
		</div>
	</div>

	<h3 class="common_title">商品列表</h3>
	
	<div class="common_list_con clearfix">
		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>		
		</ul>
        {% for sku in skus %}
		<ul class="goods_list_td clearfix">
			<li class="col01">{{ forloop.counter }}</li>
			<li class="col02"><img src="{{ sku.image.url }}"></li>
			<li class="col03">{{ sku.name }}</li>
			<li class="col04">{{ sku.unite }}</li>
			<li class="col05">{{ sku.price }}元</li>
			<li class="col06">{{ sku.count }}</li>
			<li class="col07">{{ sku.amount }}元</li>
		</ul>
        {% endfor %}
	</div>

	<h3 class="common_title">总金额结算</h3>

	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_goods_count">共<em>{{ total_count }}</em>件商品，总金额<b>{{ total_price }}元</b></div>
			<div class="transit">运费：<b>{{ transit_price }}元</b></div>
			<div class="total_pay">实付款：<b>{{ total_pay }}元</b></div>
		</div>
	</div>

	<div class="order_submit clearfix">
        {% csrf_token %}
		<a href="javascript:;" sku_ids="{{ sku_ids }}" id="order_btn">提交订单</a>
	</div>	
{% endblock body %}
{% block bottom %}
	<div class="popup_con">
		<div class="popup">
			<p>订单提交成功！</p>
		</div>
		
		<div class="mask"></div>
	</div>
{% endblock bottom %}

{% block bottomfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript">
		$('#order_btn').click(function() {
            // 获取用户选择的收货地址id 支付方式 要购买的商品的id
            addr_id = $('input[name="addr_id"]:checked').val()
            pay_method = $('input[name="pay_style"]:checked').val()
            sku_ids = $(this).attr('sku_ids')
            csrf = $('input[name="csrfmiddlewaretoken"]').val()
            // alert(addr_id+":"+pay_method+":"+sku_ids)
            // 组织参数
            params = {'addr_id':addr_id, 'pay_method':pay_method, 'sku_ids':sku_ids,
                        'csrfmiddlewaretoken':csrf}
            // 发起ajax post请求，访问/order/commit, 传递参数:addr_id pay_method sku_ids
            $.post('/order/commit', params, function (data) {
                // 进行处理
                if (data.res == 5){
                    // alert('订单创建成功')
                    localStorage.setItem('order_finish',2);
                    $('.popup_con').fadeIn('fast', function() {
                        setTimeout(function(){
                            $('.popup_con').fadeOut('fast',function(){
                                window.location.href = '/user/order/1';
                            });
                        },3000)

                    });
                }
                else{
                    alert(data.errmsg)
                }
            })
		});



	</script>
{% endblock bottomfiles %}

DjangoFrame/templates/user_center_order.html
{#{% extends 'base_user_center.html' %}#}
{#{% load staticfiles %}#}
{#{% block right_content %}#}
{#		<div class="right_content clearfix">#}
{#                {% csrf_token %}#}
{#				<h3 class="common_title2">全部订单</h3>#}
{#                {% for order in order_page %}#}
{#				<ul class="order_list_th w978 clearfix">#}
{#					<li class="col01">{{ order.create_time }}</li>#}
{#					<li class="col02">订单号：{{ order.order_id }}</li>#}
{#					<li class="col02 stress">{{ order.status_name }}</li>#}
{#				</ul>#}
{#				<table class="order_list_table w980">#}
{#					<tbody>#}
{#						<tr>#}
{#							<td width="55%">#}
{#                                {% for order_sku in order.order_skus %}#}
{#                                    <ul class="order_goods_list clearfix">#}
{#                                        <li class="col01"><img src="{{ order_sku.sku.image.url }}"></li>#}
{#                                        <li class="col02">{{ order_sku.sku.name }}<em>{{ order_sku.price }}元/{{ order_sku.sku.unite }}</em></li>#}
{#                                        <li class="col03">{{ order_sku.count }}</li>#}
{#                                        <li class="col04">{{ order_sku.amount }}元</li>#}
{#                                    </ul>#}
{#                                {% endfor %}#}
{#							</td>#}
{#							<td width="15%">{{ order.total_amount }}元(含运费:{{ order.transit_price }})</td>#}
{#							<td width="15%">{{ order.status_name }}</td>#}
{#							<td width="15%"><a href="#" order_id="{{ order.order_id }}" status="{{ order.order_status }}" class="oper_btn">去付款</a></td>#}
{#						</tr>#}
{#					</tbody>#}
{#				</table>#}
{#                {% endfor %}#}
{#				<div class="pagenation">#}
{#                    {% if order_page.has_previous %}#}
{#                    <a href="{% url 'user:order' order_page.previous_page_number %}"><上一页</a>#}
{#                    {% endif %}#}
{#                    {% for pindex in pages %}#}
{#                        {% if pindex == order_page.number %}#}
{#                        <a href="{% url 'user:order' pindex %}" class="active">{{ pindex }}</a>#}
{#                        {% else %}#}
{#                        <a href="{% url 'user:order' pindex %}">{{ pindex }}</a>#}
{#                        {% endif %}#}
{#                    {% endfor %}#}
{#                    {% if order_page.has_next %}#}
{#                    <a href="{% url 'user:order' order_page.next_page_number %}">下一页></a>#}
{#                    {% endif %}#}
{#				</div>#}
{#		</div>#}
{#{% endblock right_content %}#}
{#{% block bottomfiles %}#}
{#    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>#}
{#    <script>#}
{#    $('.oper_btn').each(function () {#}
{#        // 获取订单支付状态#}
{#        var status = $(this).attr('status')#}
{#        status_dict = {1:'去付款', 2:'待发货', 3:'查看物流', 4:'去评价', 5:'已完成'}#}
{#        $(this).text(status_dict[status])#}
{#    })#}
{#    $('.oper_btn').click(function () {#}
{#        // 获取订单支付状态#}
{#        var status = $(this).attr('status')#}
{#        // 获取订单的id#}
{#        var order_id = $(this).attr('order_id')#}
{#        if (status == 1){#}
{#            // 订单未支付#}
{#            var csrf = $('input[name="csrfmiddlewaretoken"]').val()#}
{#            // 组织参数#}
{#            var params = {'order_id':order_id, 'csrfmiddlewaretoken':csrf}#}
{#            // 发起ajax post, 访问/order/pay, 传递参数:order_id#}
{#            $.post('/order/pay', params, function (data) {#}
{#                // 进行处理#}
{#                if (data.res == 3){#}
{#                    // 引导用户到支付页面#}
{#                    window.open(data.pay_url)#}
{#                    // ajax post 访问/orde/check, 查询支付交易结果, 传递参数：order_id#}
{#                    $.post('/order/check', params, function (data) {#}
{#                        if (data.res == 4){#}
{#                            // 支付成功#}
{#                            alert('支付成功')#}
{#                            location.reload()#}
{#                        }#}
{#                        else{#}
{#                            alert(data.errmsg)#}
{#                        }#}
{#                    })#}
{#                }#}
{#                else{#}
{#                    alert(data.errmsg)#}
{#                }#}
{#            })#}
{#        }#}
{#        else if(status == 4){#}
{#            // 跳转到评论页面#}
{#            location.href = '/order/comment/'+order_id#}
{#        }#}
{#    })#}
{#    </script>#}
{#{% endblock bottomfiles %}#}


{% extends 'base_user_center.html' %}
{% load staticfiles %}
{% block right_content %}
		<div class="right_content clearfix">
                {% csrf_token %}
				<h3 class="common_title2">全部订单</h3>
                {% for order in order_page %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ order.create_time }}</li>
					<li class="col02">订单号：{{ order.order_id }}</li>
					<li class="col02 stress">{{ order.status_name }}</li>
				</ul>
				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                                {% for order_sku in order.order_skus %}
								<ul class="order_goods_list clearfix">
									<li class="col01"><img src="{{ order_sku.sku.image.url }}"></li>
									<li class="col02">{{ order_sku.sku.name }}<em>{{ order_sku.price }}元/{{ order_sku.sku.unite }}</em></li>
									<li class="col03">{{ order_sku.count }}</li>
									<li class="col04">{{ order_sku.amount }}元</li>
								</ul>
                                {% endfor %}
							</td>
							<td width="15%">{{ order.total_amount }}元(含运费:{{ order.transit_price }})</td>
							<td width="15%">{{ order.status_name }}</td>
							<td width="15%"><a href="#" order_id="{{ order.order_id }}" status="{{ order.order_status }}" class="oper_btn">去付款</a></td>
						</tr>
					</tbody>
				</table>
                {% endfor %}
				<div class="pagenation">
                    {% if order_page.has_previous %}
                    <a href="{% url 'user:order' order_page.previous_page_number %}"><上一页</a>
                    {% endif %}
                    {% for pindex in pages %}
                        {% if pindex == order_page.number %}
                        <a href="{% url 'user:order' pindex %}" class="active">{{ pindex }}</a>
                        {% else %}
                        <a href="{% url 'user:order' pindex %}">{{ pindex }}</a>
                        {% endif %}
                    {% endfor %}
                    {% if order_page.has_next %}
                    <a href="{% url 'user:order' order_page.next_page_number %}">下一页></a>
                    {% endif %}
				</div>
		</div>
{% endblock right_content %}
{% block bottomfiles %}
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script>
    $('.oper_btn').click(function () {
        // 获取订单支付状态
        var status = $(this).attr('status')
        if (status == 1){
            // 订单未支付
            // 获取订单的id
            var order_id = $(this).attr('order_id')
            var csrf = $('input[name="csrfmiddlewaretoken"]').val()
            // 组织参数
            var params = {'order_id':order_id, 'csrfmiddlewaretoken':csrf}
            // 发起ajax post, 访问/order/pay, 传递参数:order_id
            $.post('/order/pay', params, function (data) {
                // 进行处理
                if (data.res == 3){
                    // 引导用户到支付页面
                    window.open(data.pay_url)
                }
                else{
                    alert(data.errmsg)
                }
            })
        }
        else{
            // 其他操作
        }
    })
    </script>
{% endblock bottomfiles %}

DjangoFrame/templates/user_center_site.html
{% extends 'base_user_center.html' %}
{% block right_content %}
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
                        {% if address %}
						    <dd>{{ address.addr }} （{{ address.receiver }} 收） {{ address.phone }}</dd>
					    {% else %}
                            <dd>无</dd>
                        {% endif %}
                    </dl>
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form method="post" action="{% url 'user:address' %}">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="receiver">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="addr"></textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="zip_code">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="phone">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
{% endblock right_content %}